### ISSUE TITLE
咨询一个问题，rsa加密过程中，怎么通过 字符串的密钥来获取，e,d,q,p，n的值

### ISSUE THREAD

**Issue by tigerNongdahu** [yourtion/LearningMasteringAlgorithms-C#5]
发现demo里面，e,d,n这些都是直接写死的，可以使用字符串的方式，来获取e,d,n这几个值吗?

**Comment by yourtion** [comment]
字符串的方式？他们都是在加密过程使用的数字，主要用于演示加密算法的流程，具体取值方法请参考 rsa 加密算法的实现：https://en.wikipedia.org/wiki/RSA_(cryptosystem)
